config/routes.rb
EstudioVienna::Application.routes.draw do
  
  resources :user_types

  get "sessions/new"
  get "users/new"
  get "users/delete"
  get "welcome/index"
  get "welcome/contact"

  resources :booking_tools
  resources :tools
  resources :booking_times
  resources :horas
  resources :style_groups
  resources :music_styles
  resources :users
  resources :sessions

  resources :rooms do
    resources :equipment
  end

  resources :groups do
    resources :members
  end

  resources :bookings do
    resources :assistants
  end

  
  get "logout"    => "sessions#destroy",  :as => "logout"
  get "login"     => "sessions#new",      :as => "login"
  get "signup"    => "users#new",         :as => "signup"
  

  
  match 'asignartipo/:id' => 'users#asignartipo', :as => :asignartipo
  match 'editarContrasena/:id/edit_contrasena' => 'users#edit_contrasena', as: :edit_contrasena
  match 'update_contrasena/:id' => 'users#update_contrasena', as: :update_contrasena
  match 'misgrupos/:id' => 'groups#misgrupos', :as => :misgrupos
  match 'listarSolicitudes'       => 'bookings#listarSolicitudes',    as: :listarSolicitudes
  match 'cancelarSolicitud/:id'   => 'bookings#cancelarSolicitud',    as: :cancelarSolicitud
  match 'confirmarSolicitud/:id'  => 'bookings#confirmarSolicitud',   as: :confirmarSolicitud

  match 'listarReservas'          => 'bookings#listarReservas',       as: :listarReservas
  match 'controlarAsistencia'     => 'bookings#controlarAsistencia',  as: :controlarAsistencia
  match 'AsistenciaPresente/:id'  => 'bookings#AsistenciaPresente',   as: :AsistenciaPresente
  match 'AsistenciaAusente/:id'   => 'bookings#AsistenciaAusente',    as: :AsistenciaAusente
  
  match 'AsignarTool/:id'         => 'bookings#AsignarTool',          as: :AsignarTool
  match 'FinalizarReserva/:id'    => 'bookings#FinalizarReserva',     as: :FinalizarReserva
  
  match 'bloquearUsuario/:id'         => 'users#bloquearUsuario',          as: :bloquearUsuario
  match 'desbloquearUsuario/:id'      => 'users#desbloquearUsuario',       as: :desbloquearUsuario
  match 'activarUsuario/:id'      => 'users#activarUsuario',       as: :activarUsuario
  match 'viewactivar/:id'      => 'users#viewactivar',       as: :viewactivar

   root :to => 'welcome#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/assistant.rb
class Assistant < ActiveRecord::Base
  attr_accessible :instrument, :lastname, :name, :nickname, :surname

  belongs_to :booking

  ######## Validaciones ########
 validates_presence_of :name, :message => "Ingrese el nombre de asistente"
 validates_presence_of :lastname, :message => "Ingrese el apellido de asistente"
 validates_presence_of :nickname, :message => "Ingrese un apodo del asistente"
 validates_presence_of :instrument, :message => "Ingresa el instrumento que toca"

end

app/controllers/assistants_controller.rb
class AssistantsController < ApplicationController
  # GET /assistants
  # GET /assistants.json
  def index
    @assistants = Assistant.all
    @booking  = Booking.find(params[:booking_id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assistants }
    end
  end

  # GET /assistants/1
  # GET /assistants/1.json
  def show
    @assistant = Assistant.find(params[:id])
    @booking  = Booking.find(params[:booking_id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @assistant }
    end
  end

  # GET /assistants/new
  # GET /assistants/new.json
  def new
    @back = "new"
    @boton = " Agregar asistente"
    @assistant = Assistant.new
    @booking  = Booking.find(params[:booking_id])
    @day = params[:day]
    @month = params[:month]
    @year = params[:year]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @assistant }
    end
  end

  # GET /assistants/1/edit
  def edit
    @back = "edit"
    @boton = " Actualizar asistente"
    @assistant = Assistant.find(params[:id])
    @booking  = Booking.find(params[:booking_id])
  end

  # POST /assistants
  # POST /assistants.json
  def create
    @booking  = Booking.find(params[:booking_id])
    @assistant = @booking.assistants.new(params[:assistant])
    respond_to do |format|
      if @assistant.save
        format.html { redirect_to @booking, notice: 'Se ha guardado un asistente exitosamente.' }
        format.json { render json: @assistant, status: :created, location: @assistant }
      else
        format.html { render action: "new" }
        format.json { render json: @assistant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assistants/1
  # PUT /assistants/1.json
  def update
    @assistant = Assistant.find(params[:id])
    @booking  = Booking.find(params[:booking_id])
    respond_to do |format|
      if @assistant.update_attributes(params[:assistant])
        format.html { redirect_to @assistant, notice: 'Se ha actualizado un asistente exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @assistant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assistants/1
  # DELETE /assistants/1.json
  def destroy
    @assistant = Assistant.find(params[:id])
    @assistant.destroy

    respond_to do |format|
      format.html { redirect_to assistants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/assistants_helper.rb
module AssistantsHelper
end

app/views/assistants/_form.html.erb
<%= form_for [ @booking, @assistant], :validate => true  do |f| %>
  <div class="field">
    <%= f.label :Nombre  %>
    <%= f.text_field :name %>
  </div><br />
  <div class="field">
    <%= f.label :Apellido %>
    <%= f.text_field :lastname %>
  </div><br />
  <div class="field">
    <%= f.label :apodo %>
    <%= f.text_field :nickname %>
  </div><br />
 <div class="field">
    <%= f.label :instrumento %>
    <%= f.text_field :instrument %>
  </div><br />
  <div class="actions">
    <%= f.button @boton, :class => 'active icon-ok-sign btn-primary' %>
    <% if @back == "new" %>
      <%= link_to ' atras', booking_path(@booking), :class => ' icon-arrow-left btn'%>
    <% elsif @back == "edit" %>
      <%= link_to ' atras', booking_assistant_path(@booking.id, @assistant), :class => ' icon-arrow-left btn'%>
    <% end %>
  </div>
<% end %>

app/views/assistants/edit.html.erb
<div class="page-header">
<center><h2><%=t "Actualizando a: #{@assistant.name} #{@assistant.lastname}" %></h2></center>
</div>
<%= render 'form' %>

app/views/assistants/index.html.erb
<h1>Listing assistants</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Lastname</th>
    <th>Surname</th>
    <th>Instrument</th>
    <th>Nickname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assistants.each do |assistant| %>
  <tr>
    <td><%= assistant.name %></td>
    <td><%= assistant.lastname %></td>
    <td><%= assistant.surname %></td>
    <td><%= assistant.instrument %></td>
    <td><%= assistant.nickname %></td>
    <td><%= link_to 'Show', assistant %></td>
    <td><%= link_to 'Edit', edit_assistant_path(assistant) %></td>
    <td><%= link_to 'Destroy', assistant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Assistant' %>

app/views/assistants/new.html.erb
<%- model_class = Assistant-%>
<div class="page-header">
  <center><h2>Agregar un asistente</h2></center>
</div>

<%= render 'form' %>

app/views/assistants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre: </b>
  <%= @assistant.name %>
</p>

<p>
  <b>Apellido:</b>
  <%= @assistant.lastname %>
</p>
<p>
  <b>Instrumento musical:</b>
  <%= @assistant.instrument %>
</p>
<p>
  <b>Apodo: </b>
  <%= @assistant.nickname %>
</p>

<%= link_to ' atras', booking_path(@booking), :class => ' icon-arrow-left btn'%>
<%= link_to 'Edit', edit_booking_assistant_path(@booking.id, @assistant), :class => 'icon-edit btn' %> 