config/routes.rb
EstudioVienna::Application.routes.draw do
  
  resources :user_types

  get "sessions/new"
  get "users/new"
  get "users/delete"
  get "welcome/index"
  get "welcome/contact"

  resources :booking_tools
  resources :tools
  resources :booking_times
  resources :horas
  resources :style_groups
  resources :music_styles
  resources :users
  resources :sessions

  resources :rooms do
    resources :equipment
  end

  resources :groups do
    resources :members
  end

  resources :bookings do
    resources :assistants
  end

  
  get "logout"    => "sessions#destroy",  :as => "logout"
  get "login"     => "sessions#new",      :as => "login"
  get "signup"    => "users#new",         :as => "signup"
  

  
  match 'asignartipo/:id' => 'users#asignartipo', :as => :asignartipo
  match 'editarContrasena/:id/edit_contrasena' => 'users#edit_contrasena', as: :edit_contrasena
  match 'update_contrasena/:id' => 'users#update_contrasena', as: :update_contrasena
  match 'misgrupos/:id' => 'groups#misgrupos', :as => :misgrupos
  match 'listarSolicitudes'       => 'bookings#listarSolicitudes',    as: :listarSolicitudes
  match 'cancelarSolicitud/:id'   => 'bookings#cancelarSolicitud',    as: :cancelarSolicitud
  match 'confirmarSolicitud/:id'  => 'bookings#confirmarSolicitud',   as: :confirmarSolicitud

  match 'listarReservas'          => 'bookings#listarReservas',       as: :listarReservas
  match 'controlarAsistencia'     => 'bookings#controlarAsistencia',  as: :controlarAsistencia
  match 'AsistenciaPresente/:id'  => 'bookings#AsistenciaPresente',   as: :AsistenciaPresente
  match 'AsistenciaAusente/:id'   => 'bookings#AsistenciaAusente',    as: :AsistenciaAusente
  
  match 'AsignarTool/:id'         => 'bookings#AsignarTool',          as: :AsignarTool
  match 'FinalizarReserva/:id'    => 'bookings#FinalizarReserva',     as: :FinalizarReserva
  
  match 'bloquearUsuario/:id'         => 'users#bloquearUsuario',          as: :bloquearUsuario
  match 'desbloquearUsuario/:id'      => 'users#desbloquearUsuario',       as: :desbloquearUsuario
  match 'activarUsuario/:id'      => 'users#activarUsuario',       as: :activarUsuario
  match 'viewactivar/:id'      => 'users#viewactivar',       as: :viewactivar

   root :to => 'welcome#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/booking_tool.rb
class BookingTool < ActiveRecord::Base
  attr_accessible :booking_id, :tool_id
  belongs_to :tool
  belongs_to :booking
end

app/controllers/booking_tools_controller.rb
class BookingToolsController < ApplicationController
  # GET /booking_tools
  # GET /booking_tools.json
  def index
    @booking_tools = BookingTool.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @booking_tools }
    end
  end

  # GET /booking_tools/1
  # GET /booking_tools/1.json
  def show
    @booking_tool = BookingTool.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @booking_tool }
    end
  end

  # GET /booking_tools/new
  # GET /booking_tools/new.json
  def new
    @booking_tool = BookingTool.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @booking_tool }
    end
  end

  # GET /booking_tools/1/edit
  def edit
    @booking_tool = BookingTool.find(params[:id])
  end

  # POST /booking_tools
  # POST /booking_tools.json
  def create
    @booking_tool = BookingTool.new(params[:booking_tool])

    respond_to do |format|
      if @booking_tool.save
        format.html { redirect_to @booking_tool, notice: 'Booking tool was successfully created.' }
        format.json { render json: @booking_tool, status: :created, location: @booking_tool }
      else
        format.html { render action: "new" }
        format.json { render json: @booking_tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /booking_tools/1
  # PUT /booking_tools/1.json
  def update
    @booking_tool = BookingTool.find(params[:id])

    respond_to do |format|
      if @booking_tool.update_attributes(params[:booking_tool])
        format.html { redirect_to @booking_tool, notice: 'Booking tool was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @booking_tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /booking_tools/1
  # DELETE /booking_tools/1.json
  def destroy
    @booking_tool = BookingTool.find(params[:id])
    @booking_tool.destroy

    respond_to do |format|
      format.html { redirect_to booking_tools_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/booking_tools_helper.rb
module BookingToolsHelper
end

app/views/booking_tools/_form.html.erb
<%= form_for(@booking_tool) do |f| %>
  <% if @booking_tool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking_tool.errors.count, "error") %> prohibited this booking_tool from being saved:</h2>

      <ul>
      <% @booking_tool.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :booking_id %><br />
    <%= f.number_field :booking_id %>
  </div>
  <div class="field">
    <%= f.label :tool_id %><br />
    <%= f.number_field :tool_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/booking_tools/edit.html.erb
<h1>Editing booking_tool</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking_tool %> |
<%= link_to 'Back', booking_tools_path %>

app/views/booking_tools/index.html.erb
<h1>Listing booking_tools</h1>

<table>
  <tr>
    <th>Booking</th>
    <th>Tool</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @booking_tools.each do |booking_tool| %>
  <tr>
    <td><%= booking_tool.booking_id %></td>
    <td><%= booking_tool.tool_id %></td>
    <td><%= link_to 'Show', booking_tool %></td>
    <td><%= link_to 'Edit', edit_booking_tool_path(booking_tool) %></td>
    <td><%= link_to 'Destroy', booking_tool, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Booking tool', new_booking_tool_path %>

app/views/booking_tools/new.html.erb
<h1>New booking_tool</h1>

<%= render 'form' %>

<%= link_to 'Back', booking_tools_path %>

app/views/booking_tools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Booking:</b>
  <%= @booking_tool.booking_id %>
</p>

<p>
  <b>Tool:</b>
  <%= @booking_tool.tool_id %>
</p>


<%= link_to 'Edit', edit_booking_tool_path(@booking_tool) %> |
<%= link_to 'Back', booking_tools_path %>