config/routes.rb
EstudioVienna::Application.routes.draw do
  
  resources :user_types

  get "sessions/new"
  get "users/new"
  get "users/delete"
  get "welcome/index"
  get "welcome/contact"

  resources :booking_tools
  resources :tools
  resources :booking_times
  resources :horas
  resources :style_groups
  resources :music_styles
  resources :users
  resources :sessions

  resources :rooms do
    resources :equipment
  end

  resources :groups do
    resources :members
  end

  resources :bookings do
    resources :assistants
  end

  
  get "logout"    => "sessions#destroy",  :as => "logout"
  get "login"     => "sessions#new",      :as => "login"
  get "signup"    => "users#new",         :as => "signup"
  

  
  match 'asignartipo/:id' => 'users#asignartipo', :as => :asignartipo
  match 'editarContrasena/:id/edit_contrasena' => 'users#edit_contrasena', as: :edit_contrasena
  match 'update_contrasena/:id' => 'users#update_contrasena', as: :update_contrasena
  match 'misgrupos/:id' => 'groups#misgrupos', :as => :misgrupos
  match 'listarSolicitudes'       => 'bookings#listarSolicitudes',    as: :listarSolicitudes
  match 'cancelarSolicitud/:id'   => 'bookings#cancelarSolicitud',    as: :cancelarSolicitud
  match 'confirmarSolicitud/:id'  => 'bookings#confirmarSolicitud',   as: :confirmarSolicitud

  match 'listarReservas'          => 'bookings#listarReservas',       as: :listarReservas
  match 'controlarAsistencia'     => 'bookings#controlarAsistencia',  as: :controlarAsistencia
  match 'AsistenciaPresente/:id'  => 'bookings#AsistenciaPresente',   as: :AsistenciaPresente
  match 'AsistenciaAusente/:id'   => 'bookings#AsistenciaAusente',    as: :AsistenciaAusente
  
  match 'AsignarTool/:id'         => 'bookings#AsignarTool',          as: :AsignarTool
  match 'FinalizarReserva/:id'    => 'bookings#FinalizarReserva',     as: :FinalizarReserva
  
  match 'bloquearUsuario/:id'         => 'users#bloquearUsuario',          as: :bloquearUsuario
  match 'desbloquearUsuario/:id'      => 'users#desbloquearUsuario',       as: :desbloquearUsuario
  match 'activarUsuario/:id'      => 'users#activarUsuario',       as: :activarUsuario
  match 'viewactivar/:id'      => 'users#viewactivar',       as: :viewactivar

   root :to => 'welcome#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/style_group.rb
class StyleGroup < ActiveRecord::Base
  attr_accessible :group_id, :music_style_id

  belongs_to :group
  belongs_to :music_style

 end

app/controllers/style_groups_controller.rb
class StyleGroupsController < ApplicationController
  # GET /style_groups
  # GET /style_groups.json
  def index
    @style_groups = StyleGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @style_groups }
    end
  end

  # GET /style_groups/1
  # GET /style_groups/1.json
  def show
    @style_group = StyleGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @style_group }
    end
  end

  # GET /style_groups/new
  # GET /style_groups/new.json
  def new
    @style_group = StyleGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @style_group }
    end
  end

  # GET /style_groups/1/edit
  def edit
    @style_group = StyleGroup.find(params[:id])
  end

  # POST /style_groups
  # POST /style_groups.json
  def create
    @style_group = StyleGroup.new(params[:style_group])

    respond_to do |format|
      if @style_group.save
        format.html { redirect_to @style_group, notice: 'Style group was successfully created.' }
        format.json { render json: @style_group, status: :created, location: @style_group }
      else
        format.html { render action: "new" }
        format.json { render json: @style_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /style_groups/1
  # PUT /style_groups/1.json
  def update
    @style_group = StyleGroup.find(params[:id])

    respond_to do |format|
      if @style_group.update_attributes(params[:style_group])
        format.html { redirect_to @style_group, notice: 'Style group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @style_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /style_groups/1
  # DELETE /style_groups/1.json
  def destroy
    @style_group = StyleGroup.find(params[:id])
    @style_group.destroy

    respond_to do |format|
      format.html { redirect_to style_groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/style_groups_helper.rb
module StyleGroupsHelper
end

app/views/style_groups/_form.html.erb
<%= form_for(@style_group) do |f| %>
  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.number_field :group_id %>
  </div>
  <div class="field">
    <%= f.label :music_style_id %><br />
    <%= f.number_field :music_style_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/style_groups/edit.html.erb
<h1>Editing style_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @style_group %> |
<%= link_to 'Back', style_groups_path %>

app/views/style_groups/index.html.erb
<h1>Listing style_groups</h1>

<table>
  <tr>
    <th>Group</th>
    <th>Music style</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @style_groups.each do |style_group| %>
  <tr>
    <td><%= style_group.group_id %></td>
    <td><%= style_group.music_style_id %></td>
    <td><%= link_to 'Show', style_group %></td>
    <td><%= link_to 'Edit', edit_style_group_path(style_group) %></td>
    <td><%= link_to 'Destroy', style_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Style group', new_style_group_path %>

app/views/style_groups/new.html.erb
<h1>New style_group</h1>

<%= render 'form' %>

<%= link_to 'Back', style_groups_path %>

app/views/style_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Group:</b>
  <%= @style_group.group_id %>
</p>

<p>
  <b>Music style:</b>
  <%= @style_group.music_style_id %>
</p>


<%= link_to 'Edit', edit_style_group_path(@style_group) %> |
<%= link_to 'Back', style_groups_path %>