config/routes.rb
EstudioVienna::Application.routes.draw do
  
  resources :user_types

  get "sessions/new"
  get "users/new"
  get "users/delete"
  get "welcome/index"
  get "welcome/contact"

  resources :booking_tools
  resources :tools
  resources :booking_times
  resources :horas
  resources :style_groups
  resources :music_styles
  resources :users
  resources :sessions

  resources :rooms do
    resources :equipment
  end

  resources :groups do
    resources :members
  end

  resources :bookings do
    resources :assistants
  end

  
  get "logout"    => "sessions#destroy",  :as => "logout"
  get "login"     => "sessions#new",      :as => "login"
  get "signup"    => "users#new",         :as => "signup"
  

  
  match 'asignartipo/:id' => 'users#asignartipo', :as => :asignartipo
  match 'editarContrasena/:id/edit_contrasena' => 'users#edit_contrasena', as: :edit_contrasena
  match 'update_contrasena/:id' => 'users#update_contrasena', as: :update_contrasena
  match 'misgrupos/:id' => 'groups#misgrupos', :as => :misgrupos
  match 'listarSolicitudes'       => 'bookings#listarSolicitudes',    as: :listarSolicitudes
  match 'cancelarSolicitud/:id'   => 'bookings#cancelarSolicitud',    as: :cancelarSolicitud
  match 'confirmarSolicitud/:id'  => 'bookings#confirmarSolicitud',   as: :confirmarSolicitud

  match 'listarReservas'          => 'bookings#listarReservas',       as: :listarReservas
  match 'controlarAsistencia'     => 'bookings#controlarAsistencia',  as: :controlarAsistencia
  match 'AsistenciaPresente/:id'  => 'bookings#AsistenciaPresente',   as: :AsistenciaPresente
  match 'AsistenciaAusente/:id'   => 'bookings#AsistenciaAusente',    as: :AsistenciaAusente
  
  match 'AsignarTool/:id'         => 'bookings#AsignarTool',          as: :AsignarTool
  match 'FinalizarReserva/:id'    => 'bookings#FinalizarReserva',     as: :FinalizarReserva
  
  match 'bloquearUsuario/:id'         => 'users#bloquearUsuario',          as: :bloquearUsuario
  match 'desbloquearUsuario/:id'      => 'users#desbloquearUsuario',       as: :desbloquearUsuario
  match 'activarUsuario/:id'      => 'users#activarUsuario',       as: :activarUsuario
  match 'viewactivar/:id'      => 'users#viewactivar',       as: :viewactivar

   root :to => 'welcome#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :max, :price
  has_many :equipments
  has_many :bookings


  ######## Validaciones ########
  validates_numericality_of :max, :on => :create, :message => "Ingrese la capacidad maxima de personas ej. 8"
  validates_numericality_of :price, :on => :create, :message => "Ingrese el precio que cuesta por hora esta sala de ensayo ej. 3000"
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rooms }
    end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show    
    @room = Room.find(params[:id])
    @equipment = Equipment.where(:room_id => params[:id] )
          
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/new
  # GET /rooms/new.json
  def new
    @room = Room.new
    @boton = " Agregar sala de ensayo"
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
    @boton = " Actualizar sala de ensayo"
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(params[:room])

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: "La sala de ensayo #{@room.id}  ha sido creada exitosamente." }
        format.json { render json: @room, status: :created, location: @room }
      else
        format.html { render action: "new" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rooms/1
  # PUT /rooms/1.json
  def update
    @room = Room.find(params[:id])

    respond_to do |format|
      if @room.update_attributes(params[:room])
        format.html { redirect_to @room, notice: "La sala de ensayo #{@room.id}  ha sido creada exitosamente." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for @room, :html => { :class => 'form-horizontal' }, :validate => true do |f| %>
<div class="control-group">
  	<%= f.label :"Precio por hora", :class => 'control-label' %>
 	<div class="controls">
		 <%= f.number_field :price, :class => 'number_field' %>
 	</div>
	</br>
 	 <%= f.label :"Cantidad maxima permitida", :class => 'control-label' %>
 	<div class="controls">
		 <%= f.number_field :max, :class => 'number_field' %>
	 	</div>
</div>
<div class="form-actions">
	<%= f.button @boton, :class => 'active icon-ok-sign btn-primary' %>
	<%= link_to t('.cancel', :default => t("helpers.links.cancelar")), rooms_path, :class => 'btn' %>
</div>
<% end %>

app/views/rooms/edit.html.erb
<%- model_class = Room -%>
<div class="page-header">
<center><h2><%=t "Actualizar Sala de Ensayo n° #{@room.id}" %></h2></center>
</div>
<%= render :partial => 'form' %>

app/views/rooms/index.html.erb
<%- model_class = Room -%>
<div class="page-header">
  <center><h2>Listado de salas de ensayo</h2></center>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:"Numero") %></th>
      <th><%= model_class.human_attribute_name(:"Precio por hora") %></th>
      <th><%= model_class.human_attribute_name(:"Cantidad personas permitidas") %></th>
    </tr>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= link_to room.id, room_path(room) %></td>
        <td><%= room.price %></td>
        <td><%= room.max %></td>
        <td>
          <%= link_to ' Ver Detalles', room,:class => 'active icon-zoom-in btn btn-mini' %>
          <%= link_to t('.edit', :default => t("helpers.links.actualizar")),
                      edit_room_path(room), :class => 'active icon-edit btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.eliminar")),
                      room_path(room),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => "¿Estas seguro que deseas eliminar la sala numero #{room.id}?")) },
                      :class => 'active icon-trash btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.Agregar nueva sala")),
            new_room_path,
            :class => 'btn btn-primary' %>

app/views/rooms/new.html.erb
<%- model_class = Room -%>
<div class="page-header">
  <center><h2><%=t "Nueva Sala de Ensayo" %></h2></center>
</div>
<%= render :partial => 'form' %>

app/views/rooms/show.html.erb
<%- model_class = Room -%>
<div class="row">
  <div class="span10">
    <div class="page-header">
      <center><h2><%=t "Sala de ensayo n° #{@room.id}" %></h2></center>
    </div>
    <div class="row">
      <div class="span5">
        <div class="hero-unit">
          <center><h3><%= "Detalles de la sala" %></h3></br></center>
        <table border="0">
            <tr>
              <td>Precio por hora :</td>
              <td><%= @room.price %></td>               
            </tr>

            <tr>
              <td>Cantidad personas permitidas :</td>
              <td><%= @room.max %></td>              
            </tr>
            <tr>
              <td>
                </br></br>
                <%= link_to t('.edit', :default => t(" actualizar")), edit_room_path(@room), :class => 'icon-edit btn' %>

                <%= link_to t('.back', :default => t(" atras")), rooms_path, :class => ' icon-arrow-left btn'  %>
              
                <%= link_to t('.destroy', :default => t(" eliminar")), room_path(@room), :method => 'delete',
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => "¿Estas seguro que deseas eliminar la sala numero #{@room.id}?")) },
                      :class => 'active icon-trash btn btn-danger' %>
              </td>            
            </tr>          
        </table>
        </div>       
      </div> <!-- end span6 -->
      <div class="span5">
        <div class="hero-unit">
          <center><h3><%= "Equipos Asignados" %></h3></br></center>
          <table>
            <% if @equipment.count != 0 %> 
            <tr>
              <th>Equipo</th>
              <th>Marca</th>
              <th>Cantidad</th>
            </tr>

            <%else%>
              No hay equipos asignados a esta sala
            <%end%>
           
            <% @equipment.each do |e| %>
            <tr>
              <td><%= link_to e.tool, room_equipment_path(@room, e.id) %></td>
              <td><%= e.trademark %></td>
              <td><%= e.quantity %></td>
              <td><%= link_to t('.edit', :default => t(" actualizar")),
                      edit_room_equipment_path(@room.id,e), :class => 'icon-edit btn btn-mini' %>
              </td>
              <td>
              <%= link_to t('.destroy', :default => t(" eliminar")),
                      room_equipment_path(@room.id,e),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => "¿Estas seguro que deseas eliminar #{e.tool} #{e.trademark} ?")) },
                      :class => ' active icon-trash btn btn-mini btn-danger' %>
              </td>
            </tr>
            <%end%>
          </table>
          </br>
          <%= link_to ' Agregar Equipamiento', new_room_equipment_path(@room.id), :class => "icon-plus-sign btn " %>
        </div>  
      </div> <!-- end span6 -->
    </div><!-- end row -->
  </div>
</div>